import { useUser } from '@supabase/auth-helpers-react'
import Email from '../components/mail/Mail'
import MailForm from '../components/mail/MailForm'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Account from '../components/account/Account'
import Login from '../components/account/auth/Login'
import Logout from '../components/account/auth/Logout'
import { fetchAccount } from '../components/account/connectAccountScheme'
import Spinner from '../components/Spinner'
import styles from '../styles/Home.module.css'
import { AccountProps } from '../types/account'

export default function Admin() {
  const user: User = useUser()
  const [account, setAccount] = useState<AccountProps>()
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    if (user) {
      fetchAccount(user).then((res) => {
        setAccount(res)
        setLoading(false)
      })
    }
  }, [user])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex w-full justify-center py-12 '>
        {loading ? (
          <Spinner />
        ) : (
          <div className='w-auto'>
            <Account account={account} />
            <div className='py-16'>
              <MailForm />
            </div>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <Logout />
      </footer>
    </div>
  )
}
