import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Login from '../components/account/auth/Login'
import Logout from '../components/account/auth/Logout'
import { fetchAccount } from '../components/account/connectAccountScheme'
import Profile from '../components/account/Profile'
// import DropZone from '../components/image/DropZone'
import ImageRegister from '../components/image/ImageRegister'
import MailForm from '../components/mail/MailForm'
import Spinner from '../components/Spinner'
import styles from '../styles/Home.module.css'
import { AccountProps } from '../types/account'

export default function Home() {
  const email: string = 'izumiki514@gmail.com'
  const [profile, setProfile] = useState<AccountProps>()
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    fetchAccount(email).then((res) => {
      setProfile(res)
    })
  }, [email])

  if (!profile) return <Spinner />

  return (
    <div className={styles.container}>
      <Head>
        <title>ContactFormTest</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Profile profile={profile} />
        <Login />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
